version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    network_mode: bridge
    environment:
      - SPRING_PROFILES_ACTIVE=test,docker
      - POSTGRES_PASSWORD=colognow
      - POSTGRES_USER=admin
      - POSTGRES_PORT=5432
      - POSTGRES_DB=student
      - DB_HOSTNAME=admin
    ports:
      - "8080:8080"
      - "8083:8083"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=colognow
      - POSTGRES_USER=admin
      - POSTGRES_PORT=5432
      - POSTGRES_DB=student
    restart: unless-stopped
    volumes:
      - ./mnt/postgresql:/var/lib/postgresql